---

- name: /etc/harrow
  file:
    state: directory
    path: /etc/harrow
    owner: harrow
    group: harrow

- name: "create /etc/harrow/env"
  template:
    src: "etc/harrow/env.j2"
    dest: "/etc/harrow/env"
    owner: harrow
    group: harrow

- name: "create /etc/harrow/env.sh"
  template:
    src: "etc/harrow/env.sh.j2"
    dest: "/etc/harrow/env.sh"
    owner: harrow
    group: harrow
