---

- name: ensure sudo installed
  apt:
    name: sudo

- name: ensure coreutils installed
  apt:
    name: coreutils

- include: user.yml
- include: config.yml
- include: services.yml
- include: lxd-hosts.yml

- name: make dir /srv/harrow/bin
  file:
    name: /srv/harrow/bin
    state:  directory

- name: make dir /var/lib/harrow/metadata-preflight
  file:
    name: /var/lib/harrow/metadata-preflight
    owner: harrow
    group: harrow
    state:  directory

# - include: download-harrow-any.yml
#   when: harrow.backend.version

# - include: compile-harrow-any.yml
#   when: (not harrow.backend.version)
