---

- include: download-release.yml
  when: harrow.backend.version

- include: config.yml
- include: legacy-notifier-wrappers.yml
- include: lxd-hosts.yml
- include: runner-service.yml
- include: services.yml
