---
- name: make data dir on /var/lib/harrow for metadata preflight
  file:
    state: directory
    path: /var/lib/harrow/metadata-preflight
    owner: harrow
    group: harrow

- name: "install harrow-notify-about-failure service unit file"
  copy:
    src: "etc/systemd/system/harrow-notify-about-failure@.service"
    dest: "/etc/systemd/system/harrow-notify-about-failure@.service"
    mode: 0644

- name: "install notify-about-failure executable (email)"
  template:
    src: "usr/local/bin/notify-about-failure.email.j2"
    dest: "/usr/local/bin/notify-about-failure"
    mode: 0700
  when: harrow.victorops.enabled != true

- name: "install notify-about-failure executable (victorops)"
  template:
    src: "usr/local/bin/notify-about-failure.victorops.j2"
    dest: "/usr/local/bin/notify-about-failure"
    mode: 0700
  when: harrow.victorops.enabled == true

- name: "services files"
  include: service.yml
  with_items:
    - harrow
    - harrow-activity-worker
    - harrow-api
    - harrow-build-status-worker
    - harrow-git-trigger-worker
    - harrow-keymaker
    - harrow-limits
    - harrow-mail-dispatcher
    - harrow-metadata-preflight
    - harrow-postal-worker
    - harrow-notifier
    - harrow-projector
    - harrow-scheduler
    - harrow-ws
    - harrow-zob
  loop_control:
    loop_var: service_name

- name: create temp dirs for harrow
  file:
    state: directory
    path: "{{ item.value }}"
    owner: harrow
    group: harrow
  with_dict: "{{ harrow.filesystem }}"

