---

- name: "install {{ service_name }} service unit file"
  template:
    src: "etc/systemd/system/{{ service_name }}.service.j2"
    dest: "/etc/systemd/system/{{ service_name }}.service"

- name: reload changed daemons
  systemd:
    name: "{{ service_name }}"
    state: restarted
    daemon_reload: yes
    enabled: yes
