---

- name: check for current base image
  shell: "lxc image list {{ lxd.baseimage.fingerprint[0:12] }} | grep 'harrow-baseimage'"
  register: lxd_images
  ignore_errors: true
  tags:
    - lxd

- name: GET an object from AWS s3
  get_url:
    url: "https://s3-eu-west-1.amazonaws.com/harrow-baseimage/{{ lxd.baseimage.fingerprint }}.tar.gz"
    dest: "/tmp/baseimage-{{ lxd.baseimage.fingerprint }}.tar.gz"
    checksum: "sha256:{{ lxd.baseimage.fingerprint }}"
  when: lxd_images|failed
  register: new_lxd_image
  tags:
    - lxd

- name: import new baseimage
  shell: "lxc image import /tmp/baseimage-{{ lxd.baseimage.fingerprint }}.tar.gz --alias harrow-baseimage"
  when: new_lxd_image.changed
  tags:
    - lxd

