---

- name: operator root authorized keys dir
  file:
    dest: /root/.ssh
    state: directory
    mode: 0700
    owner: root
  tags:
    - lxd

- name: create fake 'nologin' shell
  file:
    path: /root/.ssh/authorized_keys
    state: touch
    owner: root
    mode: 0600
  tags:
    - lxd

- name: operator ssh key authorized keys file
  lineinfile:
    dest: /root/.ssh/authorized_keys
    line: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCS0B35/Quy13EZri74pz7E0y3K/yTx33YU8NJvB9YKdtOPmfUXufHM/ijlFnEMxKl7q+gfsoqvOXYaKVGeTDQ/Gp2LDQTcpHHoTi69BQ4K2NlPKhwjFV8YxHBsnyNapAXiOqeGSqeLm+ugMWnPU78/7bUvmxXnbv5i44FFWMEMHpZSrDRPutXa7SmrcBJwfiL4VFaa827SgNcH01WnXU8zh8PBWPMuKYAtUf3llF9i3gh9Qkhp0KNXkjUwTYEICliQA0ai02L9+Va/zUwxDPr8V5y5G1b2LMfryG+19oJwXzs1p1FM+06FBZxftMms/ECA22Ha2J34CP6Ih8JphCfW3dhWE9JuL1WtsFzKpfhmI+UZwPnTN3vv0lICorTTLqlzYFi7VOoLUg20ZfKsSQ7SHBSNaTyrV7cOGUCvjigS9lRbHKC2IvNFuQqfpLVq5B56fT3Kk7fkz85vU/0MKTvKlwgzuUMsCj9sOlagMLW1nbATFh7TX1cjhxxTr71GkM2VIw1NcxePGPeqShbZMI2SjROUATwFzcQCSrQb5Sqn8xX+LCTqNn3tdMPEp5dZlrl+QbX3Mcy3PPXJl80tJD0Br7tMdgKCNKfbDd7BQNZAv0Xq6nrp31q393xyBvrdon6DVNrDdLC1q2+U4ZE2pbIc76Rqx3vDdj6BNYMrpLEtCQ== operator'
  tags:
    - lxd
