---

- name: operator root authorized keys dir
  file:
    dest: /root/.ssh
    state: directory
    mode: 0700
    owner: root

- name: ensure authorized_keys file present
  file:
    path: /root/.ssh/authorized_keys
    state: file
    owner: root
    mode: 0600

- name: operator ssh key authorized keys file
  lineinfile:
    dest: /root/.ssh/authorized_keys
    line: "{{ item }}"
  with_items:
    # Key immediately below is deprecated and can safely be removed after Sept '17
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCS0B35/Quy13EZri74pz7E0y3K/yTx33YU8NJvB9YKdtOPmfUXufHM/ijlFnEMxKl7q+gfsoqvOXYaKVGeTDQ/Gp2LDQTcpHHoTi69BQ4K2NlPKhwjFV8YxHBsnyNapAXiOqeGSqeLm+ugMWnPU78/7bUvmxXnbv5i44FFWMEMHpZSrDRPutXa7SmrcBJwfiL4VFaa827SgNcH01WnXU8zh8PBWPMuKYAtUf3llF9i3gh9Qkhp0KNXkjUwTYEICliQA0ai02L9+Va/zUwxDPr8V5y5G1b2LMfryG+19oJwXzs1p1FM+06FBZxftMms/ECA22Ha2J34CP6Ih8JphCfW3dhWE9JuL1WtsFzKpfhmI+UZwPnTN3vv0lICorTTLqlzYFi7VOoLUg20ZfKsSQ7SHBSNaTyrV7cOGUCvjigS9lRbHKC2IvNFuQqfpLVq5B56fT3Kk7fkz85vU/0MKTvKlwgzuUMsCj9sOlagMLW1nbATFh7TX1cjhxxTr71GkM2VIw1NcxePGPeqShbZMI2SjROUATwFzcQCSrQb5Sqn8xX+LCTqNn3tdMPEp5dZlrl+QbX3Mcy3PPXJl80tJD0Br7tMdgKCNKfbDd7BQNZAv0Xq6nrp31q393xyBvrdon6DVNrDdLC1q2+U4ZE2pbIc76Rqx3vDdj6BNYMrpLEtCQ== operator-key-until-nov-2017'
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDRx2oBPQob+tF2uC55jIrvKTIaZDZXq1gXSmR5mLncCJEoh12PKF/ixAy6KPWUu0lh8EIazSIjOfHdCgm7iB3tQ0sushT7o1xkqgM8eJ6/iIPCoaXY8ERFKq3c7MFDk8Ou1hzvPQjtN0roubANGPqNL5ky6RPxq0eISJZQXFRhsMj1J+Vm7DfU7V1ucLu37KuHNQl16cbZfztijwuQug858bKnIuEdNmN9u3vjG5jKBByxVGhQAHq1T4y3Myplr+2wSvPGY2hAyMgSvj9pow3P3/lZ3zpLCCZYxhu5RTpQ/0zADZ1oX3yKoibGBZ2RcXYcvzVk7yoHyxMi4lJAh1u/ operator-ssh-key-after-september-2017'
