---

- name: ansible user in users group (like harrow, for hmac_secret)
  user:
    name: vagrant
    groups: users
    append: true
  become: true
  tags: dev

- name: Add mappings to /etc/hosts
  blockinfile:
    dest: /home/vagrant/.bashrc
    block: |
      # Set Working Directory
      cd /harrow/src/github.com/harrowio/api

      # Add Go bins to path
      export PATH=/harrow/bin:$PATH

      # Set Go-Path
      export GOPATH=/harrow/

      # Set RABBITMQ_BASE for rabbitmqctl
      export RABBITMQ_BASE=/var/lib/harrow/rabbitmq

      # Set PS1
      parse_git_branch() {
        git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
      }
      export PS1="\u@\h \[\033[32m\]\W\[\033[33m\]\$(parse_git_branch)\[\033[00m\] $ "
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
  tags: dev
