---

- name: file:/var/www/html
  file:
    state: directory
    path: /var/www/html
    mode: 0700
    owner: www-data
    group: www-data
  tags: nginx

- apt:
    name: "{{ item }}"
    update_cache: true
  with_items:
    - python-pip
    - python-virtualenv

- name: install boto3
  pip:
    name: boto

- s3:
    bucket: harrow-builds
    object: "frontend/{{ harrow.frontend.version}}-{{ harrow.environment }}/dist.tar.gz"
    dest: "/tmp/harrow-{{ harrow.frontend.version }}.tar.gz"
    mode: get
    aws_access_key: "{{ vault.aws.access_key_id }}"
    aws_secret_key: "{{ vault.aws.secret_access_key }}"
    region: eu-west-1
  register: new_dist

- name: unarchive:dist.tar.gz
  unarchive:
    src: "/tmp/harrow-{{ harrow.frontend.version }}.tar.gz"
    dest: /var/www/html
    copy: No
    owner: www-data
    group: www-data
  when: new_dist | changed
