---
- name: "apt"
  apt:
    name: "{{item}}"
  with_items:
    - awscli
    - jq
    - nginx
  tags: nginx

- name: file:s-e/default
  file:
    state: absent
    path: /etc/nginx/sites-enabled/default
  notify: reload nginx
  tags: nginx

- name: file:index.nginx-debian.html
  file:
    state: absent
    path: /var/www/html/index.nginx-debian.html
  tags: nginx

- name: file:/etc/nginx/certs/
  file:
    state: directory
    path: /etc/nginx/certs
    owner: root
    group: root
    mode: 0700
  notify: reload nginx
  tags: nginx

- name: "copy:{{ inventory_hostname }}.key"
  copy:
    dest: "/etc/nginx/certs/{{ inventory_hostname }}.key"
    content: "{{ ssl_key }}"
  notify: reload nginx
  tags: nginx

- name: "copy:{{ inventory_hostname }}.crt"
  copy:
    dest: "/etc/nginx/certs/{{ inventory_hostname }}.crt"
    content: "{{ ssl_crt }}"
  notify: reload nginx
  tags: nginx

- name: copy:s-a/site.conf
  template:
    src: etc/nginx/sites-available/site.conf.j2
    dest: "/etc/nginx/sites-available/{{ inventory_hostname }}.conf"
  notify: reload nginx
  tags: nginx

- name: file:s-e/site.conf
  file:
    state: link
    path: "/etc/nginx/sites-enabled/{{ inventory_hostname }}.conf"
    src: "/etc/nginx/sites-available/{{ inventory_hostname }}.conf"
  notify: reload nginx
  tags: nginx

- include: download-harrow-dist.yml
  when: harrow.frontend.version

