---

- hosts: all
  gather_facts: false
  vars:
    harrow:
      environment: 'production'
  tasks:
    - name: apt update
      raw: DEBIAN_FRONTEND=noninteractive apt update
      changed_when: false
    - name: apt install python apt-transport-https
      raw: dpkg -l python || DEBIAN_FRONTEND=noninteractive apt install -y python apt-transport-https
      changed_when: false
  tags:
    - base

- hosts: all
  vars:
    harrow:
      environment: 'production'
  tasks:
    - name: install apt essential packages
      apt: "pkg={{ item }} state=installed update_cache=yes"
      with_items:
        - htop
        - jq
        - sudo
        - vim
  tags:
    - base

- hosts: all
  roles:
    - harrow.base
  tags:
    - base

- hosts: lxd
  vars:
    harrow:
      environment: 'production'
  roles:
    - harrow.lxd-host
  tags:
    - lxd

- hosts: metrics
  roles:
    - harrow.metrics-host
  tags:
    - metrics
