---

- apt:
    name: "{{ item }}"
    update_cache: true
  with_items:
    - libpq-dev
    - postgresql
    - python-psycopg2
  tags: postgresql

- name: stop postgresql before lobotomising it
  systemd:
    name: postgresql
    state: stopped
  tags: postgresql

- name: /var/lib/harrow/postgresql/9.5/main
  file:
    state: directory
    path: /var/lib/harrow/postgresql/9.5/main
    owner: postgres
    group: postgres
  tags: postgresql

- lineinfile:
   dest: /etc/postgresql/9.5/main/postgresql.conf
   regexp: '^data_directory ='
   line: "data_directory = '/var/lib/harrow/postgresql/9.5/main'"
  tags: postgresql
  become: true

- name: 'fix postgresql permissions'
  file:
    path: /var/lib/harrow/postgresql/
    owner: postgres
    group: postgres
    mode: 0700
    recurse: true
  become: true
  tags: postgresql

# - name: 'check for postgresql dir files (must init?)'
#   find:
#     paths: /var/lib/harrow/postgresql
#     file_type: file
#     patterns: "*"
#   register: postgresql_dir_files
#   tags: postgresql

- name: initiate database
  command: /usr/lib/postgresql/9.5/bin/initdb -D /var/lib/harrow/postgresql/9.5/main
  become: true
  become_user: postgres
  ignore_errors: true
  tags: postgresql

- replace:
    dest: "{{ item }}"
    regexp: 'local.*all.*all.*peer'
    replace: "local   all             all                                     password"
  with_items:
    - /etc/postgresql/9.5/main/pg_hba.conf
    - /var/lib/harrow/postgresql/9.5/main/pg_hba.conf
  become: true
  tags: postgresql

- name: start post-lobotomy postgresql
  systemd:
    name: postgresql
    state: restarted
  tags: postgresql

- postgresql_db:
    name: "{{ db.name }}"
    encoding: "UTF-8"
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
    template: "template0"
    owner: 'postgres'
  with_items: "{{ harrow.postgresql.databases }}"
  loop_control:
    loop_var: db
  become: true
  become_user: postgres
  tags: postgresql

- postgresql_user:
    db: "{{ db.name }}"
    name: "{{ db.username }}"
    password: "{{ db.password }}"
  with_items: "{{ harrow.postgresql.databases }}"
  loop_control:
    loop_var: db
  become: true
  become_user: postgres
  tags: postgresql

- copy:
    dest: /etc/tmpfiles.d/postgresql-9.5.conf
    content: "D /var/run/postgresql 0775 - postgres -"
  tags: postgresql
  notify: restart postgresql

- include: pgbouncer.yml
- include: postgresql_extensions.yml
