version: '3.0'

services:

  # The Dockerfile for this image can be found in ./support/fluentd
  fluentd:
    image: harrowio/fluentd:latest
    container_name: harrow-fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./support/fluentd/fluentd.conf:/fluentd/etc/fluentd.conf
      - ./logs:/mnt/data/api-logs/
    environment:
      - FLUENTD_CONF=fluentd.conf
    links:
      - elasticsearch

  elasticsearch:
    image: elasticsearch
    container_name: harrow_elasticsearch
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana
    links:
      - elasticsearch
    ports:
      - "5601:5601"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: harrow-rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:alpine
    restart: always
    container_name: harrow-redis
    ports:
      - 6379:6379

  postgres:
    image: postgres:latest
    container_name: harrow-postgres
    restart: always
    environment:
      - POSTGRES_USER=harrow-dev-test
      - POSTGRES_PASSWORD=harrow-dev-test
    ports:
      - 5432:5432
